### ISSUE TITLE
VSCode support?

### ISSUE THREAD

**Issue by Nowhk** [willpirkleaudio/ASPiK#13]
Hi,

I'm trying to use [your ](https://github.com/willpirkleaudio/ASPiK/tree/develop/PluginTemplate/project_source/source/PluginObjects)fxobjects.zip within a project on Visual Studio Code, but it seems some macro are fixed within VS project code as preprocessor macro?

Example, I'm on Windows 10 (64 bit):

![image](https://user-images.githubusercontent.com/19835752/103544485-746d8300-4ea0-11eb-9a41-3bb1b5528ba7.png)

it should get _WINDOWS (or _WINDLL), but seems missing.
Can you support VSCode? Or how can I port it easily? Which are the parts I need to migrate?

Thanks

**Comment by willpirkleaudio** [comment]
Yes, I support VS and there is nothing to migrate or port. 

This looks like it is from fxobjects.h, which is not (technically) part of ASPiK, though you can certainly use it. You need to add a pre-processor definition in Visual Studio for _WINDOWS or _WINDLL. When I create a new Visual Studio DLL project, _WINDOWS is automatically defined in the C++ preprocessor definition, so it sounds like your project is missing this. 

You can either modify your own pre-processor defines by adding _WINDOWS, or just comment out the code to enable what you need.

I should also tell you that I am no longer using this method for generating white noise, or pure random numbers. Instead, I am using the std::default_random_engine:

#include <random>
std::default_random_engine  defaultGeneratorEngine;
		
std::uniform_real_distribution<double> randomDisribution(-1.0, 1.0);
double randomNumber =  randomDisribution(defaultGeneratorEngine);

But you may not be interested in that, only wanting to get rid of your error. 

You might want to sign up for my Forum at www.willpirkle.com where these kinds of questions pop up from time to time. 

- Will Pirkle

**Comment by Nowhk** [comment]
I meant "VSCode", not "VS" 👍 
Which pre-processor macro do I need to port? Only _WINDOWS?
I see different flags https://github.com/willpirkleaudio/ASPiK/blob/70ee0efbfb1b29c39e68db6a7fb8ae40d3654fe9/vstgui4/vstgui/tests/uidescription%20vst3/win/uidescription%20test_vs2017.vcxproj#L95

What I'm looking for is to make a plug using another framework, just migrating the fxobjects.zip as [you ](https://github.com/willpirkleaudio/ASPiK/tree/develop/PluginTemplate/project_source/source/PluginObjects)suggested

Also, it seems I need to download and use guiconstants.h, because fxobjects.h need it (so, not sure why its not included in fxobjects.zip:

![image](https://user-images.githubusercontent.com/19835752/103556285-d682b400-4eb1-11eb-98b9-6990de21883d.png)

**Comment by willpirkleaudio** [comment]
OK - guiconstants.h is part of ASPiK and that is why it is not included. You can grab it out of the ASPiK PluginKernel.

fxobjects.h/.cpp were designed to be framework agnostic from the start - they are just C++, though there are usages of C++11. 

ASPiK does not use VSCode directly, but I don't think there is anything in particular that would prevent it.

- Will

**Comment by Nowhk** [comment]
I see. Thanks for the reply. 

So, is it correct to state that this info is missing on your manual? http://www.willpirkle.com/support/juce-iplug-users/
It seems we are done just using that fxobjects.zip within (for example) IPlug plugin, but in fact it doesnt: it also need guiconstants.h (and seems only that, for the moment).

What do you think? Make sense?

**Comment by willpirkleaudio** [comment]
I have updated the fxobjects package to include the constant definitions that were missing, after running a generic test with a blank (non ASPiK completely generic) DLL project to check the missing definitions. For ASPiK users, there is no issue or anything to change; this is only for other frameworks.

I added a link to the https://www.willpirkle.com/support/juce-iplug-users/ page to download this new zip package (which should have been there anyway), therefore the page text remains the same (I did not add any new files, I altered the fxobjects.h file only). I changed the name of the zipfile to avoid other conflicts.

You can download that new package now. If you use FFTW, you will need extra files that I cannot legally provide, but you can get from fftw.org

For completeness, the missing items were:

- constant definitions of pi and 2pi
- constant definitions for envelope detector modes and time-coefficients

const double kPi = 3.14159265358979323846264338327950288419716939937510582097494459230781640628620899;

const double kTwoPi = 2.0*3.14159265358979323846264338327950288419716939937510582097494459230781640628620899;

const uint32_t ENVELOPE_DETECT_MODE_PEAK = 0;	///< |x|
const uint32_t ENVELOPE_DETECT_MODE_MS = 1;		///< (1/N)|x|^2
const uint32_t ENVELOPE_DETECT_MODE_RMS = 2;	///< SQRT((1/N)|x|^2)
const uint32_t ENVELOPE_DETECT_MODE_NONE = 3;	///< not used
const float ENVELOPE_DIGITAL_TC = -4.6051701859880913680359829093687;///< ln(1%)
const float ENVELOPE_ANALOG_TC = -1.0023934309275667804345424248947; ///< ln(36.7%)

**Comment by Nowhk** [comment]
Oh wow, nice! Now its "really" indipendent :)
Just one more thing: still don't find this using code from https://www.willpirkle.com/fx-book-bonus-material/chapter-19-addendum/:

![image](https://user-images.githubusercontent.com/19835752/103627298-b698d200-4f3d-11eb-995d-593a422ec803.png)

It seems vaFilterAlgorithm::kLPF2; its not defined? Typo? Did you mean ::kLPF1?

**Comment by willpirkleaudio** [comment]
The final plugin version, which is in the WickerAmpCombo project at my website has the corrected enumeration which is kSVF_LP, a 2nd order state variable filter LPF. 

While I appreciate your report here, this has nothing to do with ASPiK. Please use the forum at www.willpirkle.com to ask questions like this.
