### ISSUE TITLE
Windows 10: No binaries installed?

### ISSUE THREAD

**Issue by g40** [willpirkleaudio/ASPiK#41]
Apologies for the extremely vague and tentative nature of this issue but I was expecting the released installer to set up the ASPIK creator UI? It does not - is this correct?

![image](https://github.com/willpirkleaudio/ASPiK/assets/812250/7fc349dc-619b-40e0-a643-3a472591f455)

**Comment by DrWig** [comment]
That pic is of the VSTGUI editor (available in plugins once you've compiled
and loaded your plugins into a DAW).....

If you're talking about the aspik creator app to make a blank project, I
have noticed this doesn't install if you're putting the new version in a
separate folder (it detects a current version is already installed and
skips.....)

Do let me know if I've misunderstood your question....

Cheers

Bruce

**Comment by g40** [comment]
@DrWig Hi Bruce. Thanks. I will try and get a VST4 build set up. Part of the problem here is that the installer seems to only half respect the selected installation folder:

![image](https://github.com/willpirkleaudio/ASPiK/assets/812250/70e10f17-d088-4f63-9f45-8305a11f51da)

The ASPIKreator app ends up in a completely different place.

![image](https://github.com/willpirkleaudio/ASPiK/assets/812250/853e9e46-b2b0-4166-bfc9-062556e9ed24)

**Comment by DrWig** [comment]
Yes, that's the issue for the Aspikreator app.

Cheers

Bruce

**Comment by g40** [comment]
Thanks Bruce. Will close this.
